import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <footer className="site-footer">
          <div style={{ fontStyle: 'italic', fontSize: '0.75em', opacity: 0.8 }}>Events of distinction</div>
          <div style={{ fontStyle: 'italic', fontSize: '0.75em', opacity: 0.8, marginTop: '5px' }}>Tech Codestam</div>
        </footer>
      </body>
    </html>
  );
}
